### ISSUE TITLE
Create public documentation for Carnivore2

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#13]
We need to create publicly available documentation for Carnivore2 based on the current documents on Github. In English and in Russian. The documentation should have several pages:

- Description of the device + technical data + photos
- Technical description
- Changelog
- Partslist, schematics and links to Github repository with the files
- Information about current manufacturers + links to shops or personal contact info (no mails!)
- Initial installation of the cartridge
- Preparing CF card with DOS2.0
- Upgrading firmware
- Upgrading boot block and BIOSes
- Instructions for working with boot block
- Instructions for working with every provided utility
- Instructions for creating and working with RCP configuration files
- Instructions for working with MegaRAM and FMPAC SRAM
- Instructions for enabling special SCC+ mode
- Troubleshooting
- Contact info for developers

**Comment by mr-GreyWolf** [comment]
Mатериалы на русском языке:
1. [Инструкция по эксплуатации Carnivore2](https://sysadminmosaic.ru/msx/carnivore2/)
2. [Подробное техническое описание картриджа](https://sysadminmosaic.ru/msx/carnivore2/specification)

Materials in English:
1. [English manual for Carnivore2](https://sysadminmosaic.ru/msx/carnivore2/carnivore2-en)
2. [Detailed technical description of the cartridge Carnivore2](https://sysadminmosaic.ru/msx/carnivore2/specification-en)

**Comment by Wierzbowsky** [comment]
All done.
