### ISSUE TITLE
Bootblock other colours

### ISSUE THREAD

**Issue by FairFight14** [RBSC/Carnivore2#2]
Please update the other Bootblock colours to v2.06, instead of leaving them at v2.05

**Comment by Wierzbowsky** [comment]
Will do that at some point. The difference between the versions is minimal
(The Casio's built-in trigger buttons can now interrupt the autostart). If
you don't use Casio MSX, you can just stay with v2.05.

**Comment by Wierzbowsky** [comment]
Done and uploaded.

**Comment by FairFight14** [comment]
Thank you
