### ISSUE TITLE
In Boot Menu version 2.30 on GoTek emulator (in Side slot) LED is on

### ISSUE THREAD

**Issue by mr-GreyWolf** [RBSC/Carnivore2#24]
Yamaha YIS-503IIIR (MSX2, RAM 1 Mb. SubROM without CP/M)
Carnivore2 in slot 1-0 or 2-0
GoTek emulator in slot 3-3

**Comment by mr-GreyWolf** [comment]
Problem in GoTek [FlashFloppy](https://github.com/keirf/FlashFloppy)  firmware: do NOT put the FF.CFG file into any subfolder, keep it in the root folder of your USB drive!

**Comment by mr-GreyWolf** [comment]
The problem is not completely resolved:
1) after switching on if **Dual reset on cold boot: Y** = LED is off (Ok)
2) after loading and executing in C2MAN **4 - Restart the computer** - after rebooting = LED is off (Ok)
3) after rebooting, at the touch of a Reset button = LED is on

**Comment by Wierzbowsky** [comment]
Your Gotek had an anomaly (failure). Please check with another device.

**Comment by Wierzbowsky** [comment]
On-hold, pending on full repair of the Gotek (glitchy EEPROM).

**Comment by Wierzbowsky** [comment]
The Nextor's IDE driver may be the reason for that. The ticket has been created for Nestor:
https://github.com/Konamiman/Nextor/issues/64

**Comment by Wierzbowsky** [comment]
Depends on Nextor driver, nothing to do for Carnivore2.
