### ISSUE TITLE
Add a register that may store a position of last started menu entry

### ISSUE THREAD

**Issue by robodrunk** [RBSC/Carnivore2#26]
It should be something capable of storing last executed menu entry between resets (it should be fine if that value is reset to 0 after a power-off).

When user gets into Carnivore2 menu next time it should have the selection cursor set to that last executed entry.  It will greatly help with large lists of entries, like 50+

**Comment by Wierzbowsky** [comment]
We can add a new feature into the configuration screen "Remember last used entry" or something similar.

**Comment by Wierzbowsky** [comment]
Implemented. Pressing "L" key will put the cursor on the last used entry or on the DefConfig if the previously saved entry is not available. The setting is saved into the configuration EEPROM. If the entry's contents are replaced, the replaced entry will be launched.

Will be released with the new Boot Menu.

**Comment by Wierzbowsky** [comment]
Released in v2.40 on 03.07.2020
