### ISSUE TITLE
Need RCP file for run Yamaha Painter ROM

### ISSUE THREAD

**Issue by mr-GreyWolf** [RBSC/Carnivore2#28]
Please create RCP file for run **Yamaha Painter** ROM

**Comment by Wierzbowsky** [comment]
Painter is correctly identified by C2MAN as MiniROM (mapper detection fails because there's no mapper). But I created the RCP file and it will be published with the next release.

**Comment by Wierzbowsky** [comment]
Released in v2.40 on 03.07.2020
