### ISSUE TITLE
Viewing Board Design Files

### ISSUE THREAD

**Issue by techana** [RBSC/Carnivore2#3]
I tried many PCB design software, such as KiCad and Altium, but none of them could open carnivore2.sch or carnivore2.pcb files found in "Board" folder.

I wonder what programs you use to view or edit these files?

Thank you

**Comment by Wierzbowsky** [comment]
Hi,

This is a very old version of P-CAD 2006 software.

Regards,
Alexey

**Comment by techana** [comment]
Thank you so much.

I downloaded "P-CAD PCB Viewer" and was able to view the board design. But still can't figure out the push button size! Is it 6x6 or 4.5x4.5?

**Comment by Wierzbowsky** [comment]
6x6
