### ISSUE TITLE
Can't use slot 2 of AX-170 for main C2 cartridge nor dual slot

### ISSUE THREAD

**Issue by wbahnassi-if** [RBSC/Carnivore2#33]
The Sakhr AX-170 MSX1 machine has two cartridge slots. The first is mapped as slot 2-0, and the second is mapped as slot 3-3. See (https://www.msx.org/wiki/Sakhr_AX-170#Slot_Map).

If C2 is inserted into the machine's second cartridge slots,  C2 refuses to go into the boot menu, saying "Unusable slot! System Halted!"

Further more, when C2 is inserted into the first cartridge slot of the AX-170, dual slot setup is not allowed because probably C2 doesn't like dealing with slot 3-3.

Would be great if dual slot can be made to work on AX-170!

Thanks!

**Comment by wbahnassi-if** [comment]
I wonder if #22 will actually make this work too, if so, feel free to close this issue

**Comment by Wierzbowsky** [comment]
Carnivore2 doesn't work in the subslots of the expanded slots. On Yamahas slot 3 is already expanded, so the cartridge detects it and blocks further actions.

If you remove the Arabic ROM from slot 1, you will be able to use dual-slot feature of Carnivore2.

When the dual-slot feature starts supporting one of the primary subslots to be used for the emulated slot, then you will be able to use he dual-slot feature on your MSX.

**Comment by wbahnassi-if** [comment]
I can suppress the Arabic ROM by holding Ctrl during boot on the AX-170, but that doesn't seem to make C2 allow dual slot.

**Comment by Wierzbowsky** [comment]
You suppress the software's functionality, but the chip's contents are still occupying slot 1. Carnivore checks whether the slot is empty by looking for specific BIOS data at certain addresses. If it finds any data, the slot is considered unusable.

**Comment by Wierzbowsky** [comment]
The #22 is in progress, so this should solve the problem for you once the new Boot Menu is released.
