### ISSUE TITLE
Freeze when Slave Slot as Master's subslot, and selected in 2nd Master's subslot (in place of RAM)

### ISSUE THREAD

**Issue by Pencioner** [RBSC/Carnivore2#35]
Computer: Sanyo WAVY PCH-70FD
Steps to reproduce:
  1) select two roms for dual-slot setup
  2) in dual slot screen activate option "Slave Slot as Master's subslot"
  3) in master slot configuration set up slave slot in master's subslot 2 - in the place of RAM
  4) press enter to apply changes and restart - after "rebooting MSX" computer freezes

UPD: It looks like it doesn't depend on the ROMs selected for dual slot setup, it freezes anyway

**Comment by Wierzbowsky** [comment]
Happens because of dependency on RAM in the reset preparation code. Working on it...

**Comment by Wierzbowsky** [comment]
Fixed in Alpha2, will be deployed with the rest of the fixes.

**Comment by Wierzbowsky** [comment]
Released in v2.40 on 03.07.2020
