### ISSUE TITLE
Modify C2MAN and C2MAN40 to create an autostart entry for the uploaded ROM in automatic mode

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#39]
Modify C2MAN and C2MAN40 utilities to create an autostart entry for the uploaded ROM when the special command line option is selected together with /A (automatic uploading).

Consider also adding the same feature into C2RAMLDR when a directory entry for a ROM loaded into RAM is created.

**Comment by Wierzbowsky** [comment]
After creating the directory entry, this entry should be set as the default auto-start entry in the configuration EEPROM.

**Comment by MBilderbeek** [comment]
For the purpose of just running a ROM a single time, I'd rather not have the tool mess with my permanent settings (like the menu entries, EEPROM stuff, etc.). Just run the game and when you reset, it should be gone again. Basically, like Sofarun.

**Comment by Wierzbowsky** [comment]
Agree with Manuel. Rejected.
