### ISSUE TITLE
C2RAMLDR utility must find and remove previous "RAM:" entries before creating a new one

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#40]
C2RAMLDR utility must find and remove all previous "RAM:" entries before creating a new one.

Confirmation is needed before such action. Or a menu entry to find and delete RAM: entries could be added

**Comment by Wierzbowsky** [comment]
C2SRAM utility must find and remove previous "RAM:" entries before creating a new one.

**Comment by Wierzbowsky** [comment]
Fixed in version 1.41.
Added new menu option:
" 3 - Optimize and clean-up directory"
When selected, the directory is optimized and all "RAM: " entries are removed.

Also added removal of "RAM: " entries into C2MAN, C2MAN40, C2MINI and C2MINI40 utilities v2.21.

Will be released with other utilities in a few weeks.

**Comment by Wierzbowsky** [comment]
Released on 27.02.2024

**Comment by micv2** [comment]
Thanks Alexey, now c2ramldr works nicely 👍

regards,
Paul
