### ISSUE TITLE
5 volt tolerance of Cyclone II

### ISSUE THREAD

**Issue by jeroentaverne** [RBSC/Carnivore2#43]
I noticed that there are no level translators on the Carnivore II hardware. In the datasheet of the Cyclone II is mentioned that the PCI clamping diodes need to be enabled after powerup during configuration, and after this it's allowed to send 5 volts using series resistors into the Cyclone II. I was wondering if Carnivore II enables the clamping diodes, and if this happens soon enough. The MSX slot always has active 5 volt signals after powerup.

**Comment by Wierzbowsky** [comment]
According to our engineer, it's quite the opposite - the diodes must be disabled.

(1) To drive inputs higher than VCCIO but less than 4.0 V, disable the PCI clamping diode and turn on the Allow
LVTTL and LVCMOS input levels to overdrive input buffer option in the Quartus II software.

https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/hb/cyc2/cyc2_cii5v1.pdf - Page 79

However' enabling them won't hurt.
