### ISSUE TITLE
Allow Carnivore2 to run from primary slot 3

### ISSUE THREAD

**Issue by bsittler** [RBSC/Carnivore2#46]
Today Carnivore2 will halt the MSX when inserted in primary slot 3.

The National CF-3000's two cartridge slots are primary slots 2 and 3 (primary slot 1 contains the system RAM), and I'm hoping to use Carnivore2 in slot 3 together with another less-flexible cartridge in slot 2 - that other cartridge also doesn't work from primary slot 3, but unlike Carnivore 2 doesn't have any easy way to modify the firmware / cartridge ROM

**Comment by Wierzbowsky** [comment]
Implement the check whether slot 3 is expanded. If not, allow to run Carnivore2 in slot3.

**Comment by Wierzbowsky** [comment]
Implemented in boot block 2.50 with configuration setting
