### ISSUE TITLE
Introduce a new configuration entry - Autostart Countdown

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#53]
Introduce new configuration entry - Autostart Countdown in the Boot Menu. The range of values is from 0 to 9 and represent seconds to delay the autostart execution. When the value is set to zero, no autostart message should be shown and the selected directory entry is started instantly. The default value is 3. The value must be saved into the configuration EEPROM.

**Comment by MBilderbeek** [comment]
Cool, thanks! At least one can choose now to very quickly start to Nextor without any unnecessary delays. This is very useful for people who mostly use SofaRun (which is also suggested in the Carnivore 2 manual) and do not use the other items in the boot menu.

**Comment by Wierzbowsky** [comment]
Implemented in boot block 2.50
