### ISSUE TITLE
OPLL rhythm volume is very low.

### ISSUE THREAD

**Issue by uniskie** [RBSC/Carnivore2#57]
**OPLL rhythm volume is very low.**

Here is the suggested code for the fix.
https://github.com/RBSC/Carnivore2/pull/56/files#diff-bcd19d29beee62b4955a11b85dd012a57c9b256f1d6f07da3ce46587c8cdef90

Sample movies:

- Sound before modification. ... Rhythm volume is too low.
    https://twitter.com/uniskie/status/1348628086623854593

- Sound after code modification.
    https://twitter.com/uniskie/status/1348628153636278275

- (Reference) Sound of OCM (using VM2413)
    https://twitter.com/uniskie/status/1348629479585796096

**Comment by Wierzbowsky** [comment]
We've implemented our own fix based on your changes to VHD files. Now FMPAC sounds way better with all the drums and effects! Many thanks for your contribution!

The fix will be released in firmware 2.50. I can send you the alpha firmware - please contact me via the RBSC's homepage: http://rbsc.su

Please delete your pull request, we implemented the changes in our repository's VHD files.

**Comment by uniskie** [comment]
I removed pull request.
 Thank you for your support!
