### ISSUE TITLE
Auto-change Carnivore2's ID port based on the slot number

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#64]
To prevent conflicts on ID port level #F0-#F2 between different Carnivores in a system we need to change Carnivore2's port based on the slot number. This should be done in early initialization of Carnivore2 before Boot Menu. The Boot Menu reads from default port #F0 and then adjusts the port based on the slot number.

**Comment by Wierzbowsky** [comment]
Rejected because it's not possible for one Carnivore2 to know how the other Carnivore2's start at any point. The priority and booting mode is unknown, before initialization it's not clear on what port each Carnivore2 will work.

**Comment by sdsnatcher** [comment]
Is it really necessary to waste more of the scarce main I/O ports with this cartridge?

Why not use the Switched I/O ports?

I would recommend to take a look at the OneChipMSX switched I/O ports for some design inspiration.

**Comment by Wierzbowsky** [comment]
We got this feature request from 2 different software developers, so we implemented it.

**Comment by Wierzbowsky** [comment]
This can be done by querying the slot from port F0 and then depending on the slot auto-chanding the port number:

Slot 1 = Port #F0
Slot 2 = Port #F1
Slot 3 = Port #F2

A user will still be able to change the port number if necessary for the current session.

**Comment by Wierzbowsky** [comment]
The setting for port number may be set to F0, F1, F2 and -- (automatic), if automatic mode is selected, the port number is selected automatically at Boot Menu's startup based on the current slot.

**Comment by Wierzbowsky** [comment]
Implemented. When -- is selected, the port will be auto-set based on slot number. This also becomes the default setting. The automatically selected port is shown near the setting

![cmfc_config](https://user-images.githubusercontent.com/16538424/145097913-bdfae6cb-14b2-4747-b35a-c1b718e68af6.jpg)
