### ISSUE TITLE
still Freezes when used with KONAMI SCC SOUND CARTRIDGE on A1GT

### ISSUE THREAD

**Issue by uniskie** [RBSC/Carnivore2#73]
firmware 2.5.0 is still
"Panasonic A1GT+KONAMI SOUND CARTRIDGE+Carnivore2" seems to stop.

It freezes or resets before running dos/nextor.

Unlike the beta version, CASIO MX-10,1ChipMSX,Panasonic A1(MSX2) have no problem. it occurs only on Panasonic A1GT(tR).

After running BootMenu 2.5.2, it occurs more frequently.

After that, even after rewriting "Erase all EPROMs with C2MAN" -> "firmware2.4.0" -> "firmware2.50+BootMenu2.5.0", the problem still occurs.

Note 1: I had never had this problem with bootMenu 2.5.0, which I had booted at least 20 times before using bootMenu 2.5.2. However, it may be that I did not test enough).

Note 2: In rare cases, after a day's time, the system will boot normally to DOS, but even in such cases, the problem will reappear after a reset or power cycle.

Note 3: With firmware 2.4.0, there is no problem with any combination.

Note 4: This problem is not reproduced by emulation with OpenMSX.

Translated with www.DeepL.com/Translator (free version)

**Comment by Wierzbowsky** [comment]
I will need to test this on real hardware. But the problem is, that I have no separate SCC cartridge and I have only TurboR ST, not GT. Is the problem reproducible on ST?

**Comment by Wierzbowsky** [comment]
Not possible to test as no hardware to reproduce is available.
