### ISSUE TITLE
Pushing Enter in the Dual-Slot Setup page is not applying changes and restarting on bootmenu v2.50

### ISSUE THREAD

**Issue by cristianoag** [RBSC/Carnivore2#74]
Using boot menu v2.50.
I'm able to change the configuration on the dual-slot setup window successfully, but when pushing enter, the configuration is not being applied and te computer is not being restarted.

![289380329_5297839500292400_5004399024764072018_n](https://user-images.githubusercontent.com/48498602/176915903-44b8715f-d948-4627-9034-ff1f48574b0a.jpg)

Using c2man to create new configurations works ok. Is that an expected behavior? If yes, the screen needs to be changed as Enter is not working to apply the configuration and restarting anymore.

**Comment by Wierzbowsky** [comment]
Yes, this is done on purpose. Until at least one meaningful entry is selected for either slot, executing configuration with Enter won't work.
