### ISSUE TITLE
Force 40 Column Mode for C2 Tools on MSX2?

### ISSUE THREAD

**Issue by rattboi** [RBSC/Carnivore2#77]
I'd like to be able to use the utilities like c2man in 40-column mode on my MSX2. It seems it doesn't matter if I use c2man.com or c2man40.com, each runs in 80-column mode on my Panasonic FS-A1.

I'm currently running over composite video on a lowish TVL display and 80-column is very hard to read.

**Comment by Wierzbowsky** [comment]
C2MAN is not designed to work in 40 column mode. I've made a fix for C2MAN40 to detect the current width. If the width of the screen is 41 columns or higher, it will switch to 80 columns mode, if the width is 40 columns or lower, it will switch to 40 columns mode. The utilities have been deployed into the repository. Please test and report here, thanks.

**Comment by rattboi** [comment]
I tried both binaries and both acted as you described.

`C2MAN40` keeps whatever mode you start it in. Tried starting it from 40-column and 80-column mode.
`C2MAN` goes into 80-column mode, regardless of start mode.

Thanks so much :)
