### ISSUE TITLE
C2MAN.COM not enough memory

### ISSUE THREAD

**Issue by Braniegk** [RBSC/Carnivore2#80]
Hi everyone. I've a problem with the C2MAN.COM program. When I try to boot from Nextor command line I recieve the message "Not enough memory".  Just happens with the last version of C2MAN, and I don't know why...
I have a FS-A1ST with 256 Kbytes of RAM and I use the last version of NEXTOR.SYS

Thanks !!!

**Comment by Wierzbowsky** [comment]
Does your MSX show the 1280kb RAM when booting?

Do you use the latest C2MAN program downloaded from the repository?
https://github.com/RBSC/Carnivore2/tree/master/Util

Try using C2MAN40 - it's slightly smaller. Also try booting your MSX with CTRL key pressed to disable the second FDD's buffers.

Please also enable the Dual-Reset feature in the configuration settings of the Boot Menu.

**Comment by Braniegk** [comment]
Hi Alex! First of all thanks for your answer. Yep, my Turbo-R show me 1280 Kbytes of RAM and Dual-Reset is enabled. I also pressed the CTRL key at startup but the result is the same.

Regarding C2MAN.COM and C2MAN40.COM, I downloaded the latest versions from the official repository. These versions are the ones that give me the "Not enough memory" error.

However, if I use old versions that I had in an old sd card image it works without problem, but of course, with these old versions I can't write the latest releases of the IDE driver, Boot Menu and FM-PAC.

Right now I can only write Boot Menu 2.40 and IDE driver 0.1.5. My firmware is 2.50.

I hope this information helps you.
Thank you so much!

**Comment by Braniegk** [comment]
> Hi Alex! First of all thanks for your answer. Yep, my Turbo-R show me 1280 Kbytes of RAM and Dual-Reset is enabled. I also pressed the CTRL key at startup but the result is the same.

Regarding C2MAN.COM and C2MAN40.COM, I downloaded the latest versions from the official repository. These versions are the ones that give me the "Not enough memory" error.

However, if I use old versions that I had in an old sd card image it works without problem, but of course, with these old versions I can't write the latest releases of the IDE driver, Boot Menu and FM-PAC.

Right now I can only write Boot Menu 2.40 and IDE driver 0.1.5. My firmware is 2.50.

I hope this information helps you.
Thank you so much!

**Comment by Braniegk** [comment]
> > Hi Alex! First of all thanks for your answer. Yep, my Turbo-R show me 1280 Kbytes of RAM and Dual-Reset is enabled. I also pressed the CTRL key at startup but the result is the same.
> 
> Regarding C2MAN.COM and C2MAN40.COM, I downloaded the latest versions from the official repository. These versions are the ones that give me the "Not enough memory" error.
> 
> However, if I use old versions that I had in an old sd card image it works without problem, but of course, with these old versions I can't write the latest releases of the IDE driver, Boot Menu and FM-PAC.
> 
> Right now I can only write Boot Menu 2.40 and IDE driver 0.1.5. My firmware is 2.50.
> 
> I hope this information helps you. Thank you so much!

I've tried with a Panasonic MSX 2+ (FS-A1WX) and the result is the same, so it appears there's no physical problem (bad RAM chip, etc.).

**Comment by Wierzbowsky** [comment]
I didn't have an explanation yet, maybe in your configuration the HIMEM boundary us lower than on a usual MSX machine or there's some anomaly with the tools. What is the exact size (in bytes) of the c2man and c2man40 files on your disk? Do you have additional drives/partitions mapped?

As you have firmware 2.50, you can use even the old utility to put the latest Nextor BIOS into Carnivore2. See if this helps. Even the 2.1.1 release version can be put into Carnivore2. You just need to rename the file "Nextor-2.1.1.SunriseIDE.MasterOnly.ROM" into BIDECMFC.BIN and flash it into the cartridge with C2MAN's Service Menu. Download the BIOS from here: https://github.com/Konamiman/Nextor/releases/tag/v2.1.1

You can also put the v2.52 Boot Block using the older C2MAN utility into Carnivore2. Did you try that?

**Comment by Wierzbowsky** [comment]
I plan to reduce the size of C2MAN by moving the editor to a different tool.

**Comment by Braniegk** [comment]
> I plan to reduce the size of C2MAN by moving the editor to a different tool.

Thank you Alex for your support!!! I expect the new version!

**Comment by Wierzbowsky** [comment]
I created the mini version of C2MAN and C2MAN40 that are, of course, called C2MINI and C2MINI40. These utilities are smaller (34kb) versions of the main utilities. They are lacking the directory entry editor, but it's still possible to delete the selected entries.

**Comment by Braniegk** [comment]
> I created the mini version of C2MAN and C2MAN40 that are, of course, called C2MINI and C2MINI40. These utilities are smaller (34kb) versions of the main utilities. They are lacking the directory entry editor, but it's still possible to delete the selected entries.

Thank you so much Alex. Are these new utilities available? I would like to try with them...

**Comment by Wierzbowsky** [comment]
Well, I have the beta version of files that I haven't tested on a real system. I can share, if you want.

**Comment by Braniegk** [comment]
> Well, I have the beta version of files that I haven't tested on a real system. I can share, if you want.

OH please let me be your beta tester!!

**Comment by Wierzbowsky** [comment]
OK, here's the beta archive for May release. You need C2MINI or C2MINI40 utility.

https://podrezov.com/carnivore2/New2/May_Release.zip

**Comment by Braniegk** [comment]
Seems that C2MINI.COM works !!!... and C2MAN.COM too !!!
Finally I could install bootmenu 2.52!
I'll try every utility :)

**Comment by Braniegk** [comment]
I can confirm thar every utility works perfectly. I'm so happy!
Thank you very much... What a great support!!!

**Comment by Wierzbowsky** [comment]
This is not yet publicly released.

**Comment by Wierzbowsky** [comment]
Released on 14.05.2023
