### ISSUE TITLE
Carnivore boots menu  no respnd on keyboard

### ISSUE THREAD

**Issue by subzero2379** [RBSC/Carnivore2#82]
My carnivore boots menu,boots sunrise. Ide when f3 pressed but on menu no reaction on keyboard commands what line i have to check

**Comment by Wierzbowsky** [comment]
I've seen this only in one case - when one of your joystick's buttons is stuck. Run the MSXDIAG ROM and see if any of your joystick's buttons is constantly pressed. This can happen even if no joystick is connected (MSX Engine chip failure). I've just had to replace S3527 chip because of that.

**Comment by subzero2379** [comment]
I use msx omega

**Comment by Wierzbowsky** [comment]
Does not matter. Test your joystick ports please.

**Comment by subzero2379** [comment]
I will remove the ls who controls joystic ports

**Comment by subzero2379** [comment]
Fixed a broken ls and works ok thanks

**Comment by Wierzbowsky** [comment]
Cool!
