### ISSUE TITLE
Help, after 1 hour Carnivore2 causes image disturbances.

### ISSUE THREAD

**Issue by micv2** [RBSC/Carnivore2#83]
Hi Alexey, we know each other from before (EEPROM) 😉

I now have the problem that when the Carnivore2 gets warm, the image on the screen floats. If I take off the Carnivore2, the image is sharp and stable. My Philips has new capacitors and an overhauled power supply. I can run the Philips for hours without any problems playing games & demos with Gotek. If I use the Carnivore2, the image problems start after about 1 hour. Sometimes even earlier. If I take the carnivore off again, the picture is perfect again. What could it be and what can I do? 

Carnivore2 is completely up to date (firmware).

Best regards,
Paul

**Comment by Wierzbowsky** [comment]
This is the first time I hear about such problem. Does this happen in both slots? What is your MSX computer model?

**Comment by micv2** [comment]
Philips VG-8235/22

I have an early Carnivore2 model from 8bits4ever. It's a strange error, I've been looking for a long time. I'll try to take photos.

**Comment by micv2** [comment]
![IMG_4041](https://github.com/RBSC/Carnivore2/assets/45406373/4f0ee007-84ec-4da8-8243-598d2b1c6749)
![IMG_4042](https://github.com/RBSC/Carnivore2/assets/45406373/64e21951-99d4-4fee-9dfa-ad38a6f24f95)
![IMG_4043](https://github.com/RBSC/Carnivore2/assets/45406373/c4eaab65-6b24-4825-882a-502a2b8b6ca1)

2x after 40Min with C2, 1x after 20Min, or quickly pulled out C2. 
Look at the lines..

**Comment by Wierzbowsky** [comment]
Interesting, could be power fluctuation. Can you test your C2 in another computer? Does this happen with any other complex cartridge?

**Comment by micv2** [comment]
Hi, at the moment I don't know anyone who has an MSX2. My MSX2 colleague died two years ago. Carnivore2 is my only MSX cartridge. Alexey doesn't rush. I now know that my Carnivore needs to cool down 😉  (or my Philips). I wish you and your team a Merry Christmas 🎄

**Comment by micv2** [comment]
Hello Alexey,
today I inserted the Carnivore2 into Slot2 (rear). I've been playing for hours now and the error doesn't appear! What is different now in Slot2? So it seems to be a Philips problem after all. If you have an idea for me? 

Greetings 🎄
Paul 

[philips_vg8235.pdf](https://github.com/RBSC/Carnivore2/files/13760387/philips_vg8235.pdf)

**Comment by Wierzbowsky** [comment]
RepairBas knows Philips systems way better than me. Please ask him. His site: https://bas-ditta.info

**Comment by micv2** [comment]
I found that C2 in Slot1 I can work around the problem. When I've played or watched a demo, I'm not allowed to quickly press the reset button. Then the image quality is usually disturbed. I press the reset button for at least 5 seconds. long, the picture is good. No idea what's going on, Philips - initializing Carnivore2?

Edit: Ok, I understood, thank you 👍

**Comment by Wierzbowsky** [comment]
I remember that Bas recommends to remove one of the coils from PSU when installing a PC drive. With that coil there is usually video disturbance when FDD motor is on. Maybe it's related. As I mentioned - try to ask Bas.

**Comment by micv2** [comment]
True, but GOTEK has no motor and the +12V is not connected. I'll ask Bas. Thanks Alex 👍🎄

Edit: Pressing the reset button a little longer is not a problem for me. My guess is that it probably has something to do with the reset circuit 👍😎
