### ISSUE TITLE
Physical button on the board does not prevent start-up.

### ISSUE THREAD

**Issue by jgilcas** [RBSC/Carnivore2#85]
Hello.

I had a problem flashing the IDE bios and I thought that the button prevented me from entering the boot menu but it did not. It is just pressing until it boots from another MSXDOS device, could it have been changed in the latest firmware?

Thanks.

**Comment by Wierzbowsky** [comment]
Please try to hold the button before powering on the computer and keep the button pressed until the other device starts booting. See if this helps.

**Comment by jgilcas** [comment]
I did a test, actually three with three different carnivores 2, I have even made a jumper with a cable to prove that indeed it does not boot, it always starts the bootmenu. Without entries in the menu is there a way not to load the IDE driver?

Thanks for your help.

**Comment by Wierzbowsky** [comment]
I just tested my own Carnivore2 with v2.50 firmware on my YIS-503III. With the button pressed before powering on my machine boots into Basic. I also tested with Carnivore2 assembled by two of our distributors. Both boot to Basic when the button is pressed and hold at power up.

What MSX computer do you test on? Is the button installed correctly? Please share a picture of the board and a video where you boot your machine with Carnivore2's button pressed. Thanks.

**Comment by Wierzbowsky** [comment]
Could not reproduce.
