### ISSUE TITLE
Cyclone 2 is not flashing with the current version of the software

### ISSUE THREAD

**Issue by HotPixelChannel** [RBSC/Carnivore2#86]
I can't flash Cyclone2 with the current software version. The chip model was selected by EPCS4. The programmer writes "**Error (210001): Can't open programming file E:/carnivore2.pof -- not valid SOF file**". At the same time, the version from 07/03/2020 was flashed normally. The programmer version is Quartus 15 Web Edition and Quartus Programmer 13. Am I doing something wrong?

**Comment by Wierzbowsky** [comment]
@HotPixelChannel The version from 07.03.2020 is 2.30. Are you trying to flash the version 2.50 from 13.04.2022 or something else? No one else reported a problem flashing v2.50 into Carnivore2 so far.

Is your cartridge from one of our official distributors?

**Comment by HotPixelChannel** [comment]
I assembled the cartridge myself. The interesting thing is that if you open a project in Quartus and flash it from the project, version v2.50 flashes well. But flashing the same version from the POF file did not work.

**Comment by Wierzbowsky** [comment]
Strange indeed. Good that you found the workaround...
