### ISSUE TITLE
On Sony Hitbit computers does not load into DOS. Only into Disk Basic.

### ISSUE THREAD

**Issue by baralgin1003** [RBSC/Carnivore2#87]
When working with a cartridge on a Sony Hitbit, there is no transition to DOS after loading. I struggled with this problem all day, the solution was found spontaneously. It turns out that you need to hold down the Del key when loading the IDE driver. I understand that this is not so much a problem with the canivor as with a third-party driver, but I would like this point to be indicated in the documentation for the cartridge. For beginners, this will be a big problem.

**Comment by Wierzbowsky** [comment]
The cartridge was tested on a variety of Sony HitBit computers and was confirmed to be working fine. The problem could be only with the build-in firmware inside those MSX computers. If the firmware gets activated, it will give you an option to exit to MSX Basic. If you select that option, the firmware will prevent loading DOS2/Nextor by Carnivore2 and force going into Basic. For this problem the special ROM was created that bypasses the built-in system firmware. You can find this ROM here:

https://github.com/RBSC/Carnivore2/tree/master/BypassFirmware

**Comment by Wierzbowsky** [comment]
Closing as there's a workaround...
